# Generated by Django 3.1.2 on 2021-02-04 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('create_team', '0004_auto_20210128_1239'),
    ]

    operations = [
        migrations.AddField(
            model_name='matches',
            name='score_a',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='matches',
            name='score_b',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='myteam',
            unique_together={('match', 'username')},
        ),
    ]
