# Generated by Django 3.1.2 on 2021-02-14 06:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('create_team', '0008_auto_20210214_1143'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myteam',
            name='user',
        ),
    ]
