# Generated by Django 3.1.2 on 2021-03-30 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('create_team', '0011_userprofilepage'),
    ]

    operations = [
        migrations.CreateModel(
            name='RsixPlayerList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('rating', models.FloatField()),
                ('totalmatch', models.IntegerField()),
            ],
        ),
    ]
