# Generated by Django 3.1.2 on 2021-01-11 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matches',
            name='competation',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='matches',
            name='team_a_flag',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='matches',
            name='team_b_flag',
            field=models.URLField(blank=True),
        ),
    ]
