# Generated by Django 3.1.2 on 2021-01-13 05:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='matches',
            unique_together={('title', 'time', 'game')},
        ),
    ]
