# Generated by Django 3.1.2 on 2021-01-12 04:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20210111_2111'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='matches',
            unique_together={('title', 'game', 'time')},
        ),
    ]
