# Generated by Django 3.1.2 on 2021-01-15 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_matches_roster'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matches',
            name='competation',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='matches',
            name='team_a_flag',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='matches',
            name='team_b_flag',
            field=models.URLField(blank=True, null=True),
        ),
    ]
