# Generated by Django 3.1.2 on 2021-01-12 04:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20210112_0932'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='matches',
            unique_together={('title', 'time')},
        ),
    ]
