# Generated by Django 3.1.2 on 2021-01-12 04:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20210112_0940'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='matches',
            unique_together={('title', 'time', 'game')},
        ),
    ]
